
export const HEADER_BACKGROUND_COLOR = '#FFF';
export const HEADER_FONT_COLOR = '#9932CC';
export const SCREEN_BACKGROUND_COLOR = '#FFF';
export const SCREEN_FONT_COLOR = '#000';
export const BUTTON_BACKGROUND_COLOR = '#9932CC';
export const BUTTON_FONT_COLOR = '#FFF';
export const COMPONENT_BACKGROUND_COLOR = '#2D2D2D';
export const COMPONENT_FONT_COLOR = '#FFF';
export const COMPONENT_BORDER_COLOR = '#FFF';

export const LIST_ITEM_BACKGROUND_COLOR = '#B0C4DE';